---
label: Theme configuration
hide_body: true
fields:
- name: hero_home
  type: file
  config:
    maxSize: 250
  label: hero_home
- type: text
  name: site_name
  label: Beyond Counsel
- type: textarea
  name: site_description
  label: Site description
- type: textarea
  name: hero_title
  config:
    wysiwyg: true
    schema:
      format: html
  label: Beyond Counsel
- type: textarea
  name: hero_subtitle
  label: Hero subtitle
  config:
    wysiwyg: true
    schema:
      format: html
- name: footer
  label: Footer text
  type: text
  hidden: false
  default: ''
- type: boolean
  name: dark_mode
  label: Dark mode
pages:
- data/theme.json
